/**
 * BestYield ABIs
 * Auto-generated by abi-migration script
 */
import { AbiContract } from '../../core';
export declare const BestYield_MAIN_V1_ABI: AbiContract;
export declare const BestYield_MAIN_V2_ABI: AbiContract;
