/**
 * CDO_EPOCH ABIs
 * Auto-generated by abi-migration script
 */
import { AbiContract } from '../../core';
export declare const CDO_EPOCH_MAIN_V1_ABI: AbiContract;
export declare const CDO_EPOCH_DEPOSIT_QUEUE_V1_ABI: AbiContract;
export declare const CDO_EPOCH_MAIN_V2_ABI: AbiContract;
export declare const CDO_EPOCH_DEPOSIT_QUEUE_V2_ABI: AbiContract;
export declare const CDO_EPOCH_MAIN_V3_ABI: AbiContract;
export declare const CDO_EPOCH_MAIN_V4_ABI: AbiContract;
export declare const CDO_EPOCH_WRITEOFF_V1_ABI: AbiContract;
