/**
 * CDO_STRATEGY ABIs
 * Auto-generated by abi-migration script
 */
import { AbiContract } from '../../core';
export declare const CDO_STRATEGY_MAIN_V1_ABI: AbiContract;
export declare const CDO_STRATEGY_MAIN_V2_ABI: AbiContract;
export declare const CDO_STRATEGY_MAIN_V3_ABI: AbiContract;
