/**
 * CDO ABIs
 * Auto-generated by abi-migration script
 */ "use strict";
Object.defineProperty(exports, "__esModule", {
    value: true
});
function _export(target, all) {
    for(var name in all)Object.defineProperty(target, name, {
        enumerable: true,
        get: all[name]
    });
}
_export(exports, {
    CDO_MAIN_V1_ABI: function() {
        return CDO_MAIN_V1_ABI;
    },
    CDO_MAIN_V2_ABI: function() {
        return CDO_MAIN_V2_ABI;
    },
    CDO_MAIN_V3_ABI: function() {
        return CDO_MAIN_V3_ABI;
    },
    CDO_MAIN_V4_ABI: function() {
        return CDO_MAIN_V4_ABI;
    }
});
const CDO_MAIN_V1_ABI = [
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: 'address',
                name: 'from',
                type: 'address'
            },
            {
                indexed: true,
                internalType: 'address',
                name: 'to',
                type: 'address'
            },
            {
                indexed: false,
                internalType: 'uint256',
                name: 'value',
                type: 'uint256'
            }
        ],
        name: 'Transfer',
        type: 'event'
    },
    {
        constant: true,
        inputs: [],
        name: 'name',
        outputs: [
            {
                name: '',
                type: 'bytes32'
            }
        ],
        payable: false,
        stateMutability: 'view',
        type: 'function'
    },
    {
        constant: true,
        inputs: [],
        name: 'totalSupply',
        outputs: [
            {
                name: '',
                type: 'uint256'
            }
        ],
        payable: false,
        stateMutability: 'view',
        type: 'function'
    },
    {
        constant: true,
        inputs: [],
        name: 'decimals',
        outputs: [
            {
                name: '',
                type: 'uint256'
            }
        ],
        payable: false,
        stateMutability: 'view',
        type: 'function'
    },
    {
        constant: true,
        inputs: [
            {
                name: 'src',
                type: 'address'
            }
        ],
        name: 'balanceOf',
        outputs: [
            {
                name: '',
                type: 'uint256'
            }
        ],
        payable: false,
        stateMutability: 'view',
        type: 'function'
    },
    {
        constant: true,
        inputs: [],
        name: 'stopped',
        outputs: [
            {
                name: '',
                type: 'bool'
            }
        ],
        payable: false,
        stateMutability: 'view',
        type: 'function'
    },
    {
        constant: true,
        inputs: [],
        name: 'owner',
        outputs: [
            {
                name: '',
                type: 'address'
            }
        ],
        payable: false,
        stateMutability: 'view',
        type: 'function'
    },
    {
        constant: true,
        inputs: [],
        name: 'symbol',
        outputs: [
            {
                name: '',
                type: 'bytes32'
            }
        ],
        payable: false,
        stateMutability: 'view',
        type: 'function'
    },
    {
        constant: true,
        inputs: [],
        name: 'authority',
        outputs: [
            {
                name: '',
                type: 'address'
            }
        ],
        payable: false,
        stateMutability: 'view',
        type: 'function'
    },
    {
        constant: true,
        inputs: [
            {
                name: 'src',
                type: 'address'
            },
            {
                name: 'guy',
                type: 'address'
            }
        ],
        name: 'allowance',
        outputs: [
            {
                name: '',
                type: 'uint256'
            }
        ],
        payable: false,
        stateMutability: 'view',
        type: 'function'
    }
];
const CDO_MAIN_V2_ABI = [
    {
        inputs: [],
        name: 'AAStaking',
        outputs: [
            {
                internalType: 'address',
                name: '',
                type: 'address'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [],
        name: 'AATranche',
        outputs: [
            {
                internalType: 'address',
                name: '',
                type: 'address'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [],
        name: 'BBStaking',
        outputs: [
            {
                internalType: 'address',
                name: '',
                type: 'address'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [],
        name: 'BBTranche',
        outputs: [
            {
                internalType: 'address',
                name: '',
                type: 'address'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [],
        name: 'FULL_ALLOC',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [],
        name: 'AA_RATIO_LIM_UP',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [],
        name: 'AA_RATIO_LIM_DOWN',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [],
        name: 'MAX_FEE',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [],
        name: 'ONE_TRANCHE_TOKEN',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [],
        name: 'allowAAWithdraw',
        outputs: [
            {
                internalType: 'bool',
                name: '',
                type: 'bool'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [],
        name: 'allowBBWithdraw',
        outputs: [
            {
                internalType: 'bool',
                name: '',
                type: 'bool'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [],
        name: 'fee',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [],
        name: 'feeReceiver',
        outputs: [
            {
                internalType: 'address',
                name: '',
                type: 'address'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [
            {
                internalType: 'address',
                name: '_tranche',
                type: 'address'
            }
        ],
        name: 'getApr',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [],
        name: 'getContractValue',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [],
        name: 'getCurrentAARatio',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [
            {
                internalType: 'address',
                name: '_tranche',
                type: 'address'
            }
        ],
        name: 'getIdealApr',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [],
        name: 'getIncentiveTokens',
        outputs: [
            {
                internalType: 'address[]',
                name: '',
                type: 'address[]'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [],
        name: 'governanceRecoveryFund',
        outputs: [
            {
                internalType: 'address',
                name: '',
                type: 'address'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [],
        name: 'guardian',
        outputs: [
            {
                internalType: 'address',
                name: '',
                type: 'address'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [],
        name: 'idealRange',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [],
        name: 'latestHarvestBlock',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        name: 'incentiveTokens',
        outputs: [
            {
                internalType: 'address',
                name: '',
                type: 'address'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [],
        name: 'isAYSActive',
        outputs: [
            {
                internalType: 'bool',
                name: '',
                type: 'bool'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [],
        name: 'lastNAVAA',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [],
        name: 'lastNAVBB',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [],
        name: 'lastStrategyPrice',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [],
        name: 'limit',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [],
        name: 'oneToken',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [],
        name: 'owner',
        outputs: [
            {
                internalType: 'address',
                name: '',
                type: 'address'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [],
        name: 'paused',
        outputs: [
            {
                internalType: 'bool',
                name: '',
                type: 'bool'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [],
        name: 'priceAA',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [],
        name: 'priceBB',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [],
        name: 'rebalancer',
        outputs: [
            {
                internalType: 'address',
                name: '',
                type: 'address'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [],
        name: 'releaseBlocksPeriod',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [],
        name: 'revertIfTooLow',
        outputs: [
            {
                internalType: 'bool',
                name: '',
                type: 'bool'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [],
        name: 'skipDefaultCheck',
        outputs: [
            {
                internalType: 'bool',
                name: '',
                type: 'bool'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [],
        name: 'strategy',
        outputs: [
            {
                internalType: 'address',
                name: '',
                type: 'address'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [],
        name: 'strategyToken',
        outputs: [
            {
                internalType: 'address',
                name: '',
                type: 'address'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [],
        name: 'token',
        outputs: [
            {
                internalType: 'address',
                name: '',
                type: 'address'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [],
        name: 'trancheAPRSplitRatio',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [],
        name: 'trancheIdealWeightRatio',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [
            {
                internalType: 'address',
                name: '_tranche',
                type: 'address'
            }
        ],
        name: 'tranchePrice',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [],
        name: 'unclaimedFees',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [],
        name: 'unlentPerc',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [
            {
                internalType: 'address',
                name: '_tranche',
                type: 'address'
            }
        ],
        name: 'virtualPrice',
        outputs: [
            {
                internalType: 'uint256',
                name: '_virtualPrice',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [],
        name: 'weth',
        outputs: [
            {
                internalType: 'address',
                name: '',
                type: 'address'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    }
];
const CDO_MAIN_V3_ABI = [
    {
        inputs: [],
        stateMutability: 'nonpayable',
        type: 'constructor'
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: 'address',
                name: 'contractAddress',
                type: 'address'
            },
            {
                indexed: true,
                internalType: 'address',
                name: 'user',
                type: 'address'
            },
            {
                indexed: false,
                internalType: 'uint256',
                name: 'susdeAmount',
                type: 'uint256'
            }
        ],
        name: 'NewCooldownRequestContract',
        type: 'event',
        signature: '0x0875f984d399481808e74d1c55a52755ad5d9b64efbdb91071be9b21b578b476'
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: 'address',
                name: 'previousOwner',
                type: 'address'
            },
            {
                indexed: true,
                internalType: 'address',
                name: 'newOwner',
                type: 'address'
            }
        ],
        name: 'OwnershipTransferred',
        type: 'event',
        signature: '0x8be0079c531659141344cd1fd0a4f28419497f9722a3daafe3b4186f6b6457e0'
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: false,
                internalType: 'address',
                name: 'account',
                type: 'address'
            }
        ],
        name: 'Paused',
        type: 'event',
        signature: '0x62e78cea01bee320cd4e420270b5ea74000d11b0c9f74754ebdbfc544b05a258'
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: false,
                internalType: 'address',
                name: 'account',
                type: 'address'
            }
        ],
        name: 'Unpaused',
        type: 'event',
        signature: '0x5db9ee0a495bf2e6ff9c91a7834c1ba4fdd244a5e8aa4e537bd38aeae4b073aa'
    },
    {
        inputs: [],
        name: 'AAStaking',
        outputs: [
            {
                internalType: 'address',
                name: '',
                type: 'address'
            }
        ],
        stateMutability: 'view',
        type: 'function',
        constant: true,
        signature: '0xeb120bf4'
    },
    {
        inputs: [],
        name: 'AATranche',
        outputs: [
            {
                internalType: 'address',
                name: '',
                type: 'address'
            }
        ],
        stateMutability: 'view',
        type: 'function',
        constant: true,
        signature: '0x44966ba0'
    },
    {
        inputs: [],
        name: 'BBStaking',
        outputs: [
            {
                internalType: 'address',
                name: '',
                type: 'address'
            }
        ],
        stateMutability: 'view',
        type: 'function',
        constant: true,
        signature: '0x15c44b8b'
    },
    {
        inputs: [],
        name: 'BBTranche',
        outputs: [
            {
                internalType: 'address',
                name: '',
                type: 'address'
            }
        ],
        stateMutability: 'view',
        type: 'function',
        constant: true,
        signature: '0xe3e39368'
    },
    {
        inputs: [],
        name: 'FULL_ALLOC',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function',
        constant: true,
        signature: '0xdfd5b1c9'
    },
    {
        inputs: [],
        name: 'AA_RATIO_LIM_UP',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function',
        constant: true,
        signature: '0xd30d2be2'
    },
    {
        inputs: [],
        name: 'AA_RATIO_LIM_DOWN',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function',
        constant: true,
        signature: '0xe913a6aa'
    },
    {
        inputs: [],
        name: 'MAX_FEE',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function',
        constant: true,
        signature: '0xbc063e1a'
    },
    {
        inputs: [],
        name: 'ONE_TRANCHE_TOKEN',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function',
        constant: true,
        signature: '0xc9aba356'
    },
    {
        inputs: [
            {
                internalType: 'uint256',
                name: '_limit',
                type: 'uint256'
            }
        ],
        name: '_setLimit',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
        signature: '0x408f3a30'
    },
    {
        inputs: [],
        name: 'allowAAWithdraw',
        outputs: [
            {
                internalType: 'bool',
                name: '',
                type: 'bool'
            }
        ],
        stateMutability: 'view',
        type: 'function',
        constant: true,
        signature: '0x55c70701'
    },
    {
        inputs: [],
        name: 'allowBBWithdraw',
        outputs: [
            {
                internalType: 'bool',
                name: '',
                type: 'bool'
            }
        ],
        stateMutability: 'view',
        type: 'function',
        constant: true,
        signature: '0x9d3ef4b2'
    },
    {
        inputs: [
            {
                internalType: 'uint256',
                name: '_amount',
                type: 'uint256'
            }
        ],
        name: 'depositAA',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'nonpayable',
        type: 'function',
        signature: '0xb450dfce'
    },
    {
        inputs: [
            {
                internalType: 'uint256',
                name: '_amount',
                type: 'uint256'
            },
            {
                internalType: 'address',
                name: '_referral',
                type: 'address'
            }
        ],
        name: 'depositAARef',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'nonpayable',
        type: 'function',
        signature: '0xd816f5dc'
    },
    {
        inputs: [
            {
                internalType: 'uint256',
                name: '_amount',
                type: 'uint256'
            }
        ],
        name: 'depositBB',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'nonpayable',
        type: 'function',
        signature: '0xe70875ad'
    },
    {
        inputs: [
            {
                internalType: 'uint256',
                name: '_amount',
                type: 'uint256'
            },
            {
                internalType: 'address',
                name: '_referral',
                type: 'address'
            }
        ],
        name: 'depositBBRef',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'nonpayable',
        type: 'function',
        signature: '0x2cc0800e'
    },
    {
        inputs: [],
        name: 'emergencyShutdown',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
        signature: '0x3403c2fc'
    },
    {
        inputs: [],
        name: 'fee',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function',
        constant: true,
        signature: '0xddca3f43'
    },
    {
        inputs: [],
        name: 'feeReceiver',
        outputs: [
            {
                internalType: 'address',
                name: '',
                type: 'address'
            }
        ],
        stateMutability: 'view',
        type: 'function',
        constant: true,
        signature: '0xb3f00674'
    },
    {
        inputs: [
            {
                internalType: 'address',
                name: '_tranche',
                type: 'address'
            }
        ],
        name: 'getApr',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function',
        constant: true,
        signature: '0x29811ee5'
    },
    {
        inputs: [],
        name: 'getContractValue',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function',
        constant: true,
        signature: '0xdc82697c'
    },
    {
        inputs: [],
        name: 'getCurrentAARatio',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function',
        constant: true,
        signature: '0x25cdd860'
    },
    {
        inputs: [
            {
                internalType: 'address',
                name: '_tranche',
                type: 'address'
            }
        ],
        name: 'getIdealApr',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function',
        constant: true,
        signature: '0xe14488e4'
    },
    {
        inputs: [],
        name: 'getIncentiveTokens',
        outputs: [
            {
                internalType: 'address[]',
                name: '',
                type: 'address[]'
            }
        ],
        stateMutability: 'view',
        type: 'function',
        constant: true,
        signature: '0x3b28d537'
    },
    {
        inputs: [],
        name: 'governanceRecoveryFund',
        outputs: [
            {
                internalType: 'address',
                name: '',
                type: 'address'
            }
        ],
        stateMutability: 'view',
        type: 'function',
        constant: true,
        signature: '0x387af1bd'
    },
    {
        inputs: [],
        name: 'guardian',
        outputs: [
            {
                internalType: 'address',
                name: '',
                type: 'address'
            }
        ],
        stateMutability: 'view',
        type: 'function',
        constant: true,
        signature: '0x452a9320'
    },
    {
        inputs: [
            {
                internalType: 'bool',
                name: '_skipRedeem',
                type: 'bool'
            },
            {
                internalType: 'bool',
                name: '_skipIncentivesUpdate',
                type: 'bool'
            },
            {
                internalType: 'bool',
                name: '_skipFeeDeposit',
                type: 'bool'
            },
            {
                internalType: 'bool[]',
                name: '_skipReward',
                type: 'bool[]'
            },
            {
                internalType: 'uint256[]',
                name: '_minAmount',
                type: 'uint256[]'
            },
            {
                internalType: 'uint256[]',
                name: '_sellAmounts',
                type: 'uint256[]'
            }
        ],
        name: 'harvest',
        outputs: [
            {
                internalType: 'uint256[]',
                name: '_soldAmounts',
                type: 'uint256[]'
            },
            {
                internalType: 'uint256[]',
                name: '_swappedAmounts',
                type: 'uint256[]'
            }
        ],
        stateMutability: 'nonpayable',
        type: 'function',
        signature: '0x5b9ba38c'
    },
    {
        inputs: [],
        name: 'idealRange',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function',
        constant: true,
        signature: '0x2047782a'
    },
    {
        inputs: [],
        name: 'latestHarvestBlock',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function',
        constant: true,
        signature: '0x81f5ae7e'
    },
    {
        inputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        name: 'incentiveTokens',
        outputs: [
            {
                internalType: 'address',
                name: '',
                type: 'address'
            }
        ],
        stateMutability: 'view',
        type: 'function',
        constant: true,
        signature: '0x2a3e4dc2'
    },
    {
        inputs: [
            {
                internalType: 'uint256',
                name: '_limit',
                type: 'uint256'
            },
            {
                internalType: 'address',
                name: '_guardedToken',
                type: 'address'
            },
            {
                internalType: 'address',
                name: '_governanceFund',
                type: 'address'
            },
            {
                internalType: 'address',
                name: '_owner',
                type: 'address'
            },
            {
                internalType: 'address',
                name: '_rebalancer',
                type: 'address'
            },
            {
                internalType: 'address',
                name: '_strategy',
                type: 'address'
            },
            {
                internalType: 'uint256',
                name: '_trancheAPRSplitRatio',
                type: 'uint256'
            },
            {
                internalType: 'uint256',
                name: '_trancheIdealWeightRatio',
                type: 'uint256'
            },
            {
                internalType: 'address[]',
                name: '_incentiveTokens',
                type: 'address[]'
            }
        ],
        name: 'initialize',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
        signature: '0x18dc7195'
    },
    {
        inputs: [],
        name: 'isAYSActive',
        outputs: [
            {
                internalType: 'bool',
                name: '',
                type: 'bool'
            }
        ],
        stateMutability: 'view',
        type: 'function',
        constant: true,
        signature: '0x1a7e0ce5'
    },
    {
        inputs: [],
        name: 'lastNAVAA',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function',
        constant: true,
        signature: '0x62adade5'
    },
    {
        inputs: [],
        name: 'lastNAVBB',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function',
        constant: true,
        signature: '0xfe81a024'
    },
    {
        inputs: [],
        name: 'lastStrategyPrice',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function',
        constant: true,
        signature: '0xfdf4c0dc'
    },
    {
        inputs: [],
        name: 'limit',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function',
        constant: true,
        signature: '0xa4d66daf'
    },
    {
        inputs: [
            {
                internalType: 'uint256',
                name: '_amount',
                type: 'uint256'
            },
            {
                internalType: 'bool',
                name: '_revertIfNeeded',
                type: 'bool'
            }
        ],
        name: 'liquidate',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'nonpayable',
        type: 'function',
        signature: '0x2758db0c'
    },
    {
        inputs: [],
        name: 'oneToken',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function',
        constant: true,
        signature: '0xa27eccc1'
    },
    {
        inputs: [],
        name: 'owner',
        outputs: [
            {
                internalType: 'address',
                name: '',
                type: 'address'
            }
        ],
        stateMutability: 'view',
        type: 'function',
        constant: true,
        signature: '0x8da5cb5b'
    },
    {
        inputs: [],
        name: 'pause',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
        signature: '0x8456cb59'
    },
    {
        inputs: [],
        name: 'paused',
        outputs: [
            {
                internalType: 'bool',
                name: '',
                type: 'bool'
            }
        ],
        stateMutability: 'view',
        type: 'function',
        constant: true,
        signature: '0x5c975abb'
    },
    {
        inputs: [],
        name: 'priceAA',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function',
        constant: true,
        signature: '0x12361ac2'
    },
    {
        inputs: [],
        name: 'priceBB',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function',
        constant: true,
        signature: '0x400f7d32'
    },
    {
        inputs: [],
        name: 'rebalancer',
        outputs: [
            {
                internalType: 'address',
                name: '',
                type: 'address'
            }
        ],
        stateMutability: 'view',
        type: 'function',
        constant: true,
        signature: '0x01d22ccd'
    },
    {
        inputs: [],
        name: 'releaseBlocksPeriod',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function',
        constant: true,
        signature: '0xedd636fb'
    },
    {
        inputs: [],
        name: 'renounceOwnership',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
        signature: '0x715018a6'
    },
    {
        inputs: [],
        name: 'revertIfTooLow',
        outputs: [
            {
                internalType: 'bool',
                name: '',
                type: 'bool'
            }
        ],
        stateMutability: 'view',
        type: 'function',
        constant: true,
        signature: '0x6f47d99b'
    },
    {
        inputs: [
            {
                internalType: 'bool',
                name: '_allowed',
                type: 'bool'
            }
        ],
        name: 'setAllowAAWithdraw',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
        signature: '0xcc115805'
    },
    {
        inputs: [
            {
                internalType: 'bool',
                name: '_allowed',
                type: 'bool'
            }
        ],
        name: 'setAllowBBWithdraw',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
        signature: '0x8f5aa090'
    },
    {
        inputs: [
            {
                internalType: 'uint256',
                name: '_fee',
                type: 'uint256'
            }
        ],
        name: 'setFee',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
        signature: '0x69fe0e2d'
    },
    {
        inputs: [
            {
                internalType: 'address',
                name: '_feeReceiver',
                type: 'address'
            }
        ],
        name: 'setFeeReceiver',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
        signature: '0xefdcd974'
    },
    {
        inputs: [
            {
                internalType: 'address',
                name: '_guardian',
                type: 'address'
            }
        ],
        name: 'setGuardian',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
        signature: '0x8a0dac4a'
    },
    {
        inputs: [
            {
                internalType: 'uint256',
                name: '_idealRange',
                type: 'uint256'
            }
        ],
        name: 'setIdealRange',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
        signature: '0x812e43fa'
    },
    {
        inputs: [
            {
                internalType: 'address[]',
                name: '_incentiveTokens',
                type: 'address[]'
            }
        ],
        name: 'setIncentiveTokens',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
        signature: '0x7692ee0a'
    },
    {
        inputs: [
            {
                internalType: 'bool',
                name: '_isStkAAVEActive',
                type: 'bool'
            }
        ],
        name: 'setIsStkAAVEActive',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
        signature: '0xeb67acb5'
    },
    {
        inputs: [
            {
                internalType: 'address',
                name: '_rebalancer',
                type: 'address'
            }
        ],
        name: 'setRebalancer',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
        signature: '0x6cfd1553'
    },
    {
        inputs: [
            {
                internalType: 'uint256',
                name: '_releaseBlocksPeriod',
                type: 'uint256'
            }
        ],
        name: 'setReleaseBlocksPeriod',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
        signature: '0x94929dc1'
    },
    {
        inputs: [
            {
                internalType: 'bool',
                name: '_allowed',
                type: 'bool'
            }
        ],
        name: 'setRevertIfTooLow',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
        signature: '0xe07eace6'
    },
    {
        inputs: [
            {
                internalType: 'bool',
                name: '_allowed',
                type: 'bool'
            }
        ],
        name: 'setSkipDefaultCheck',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
        signature: '0x46840590'
    },
    {
        inputs: [
            {
                internalType: 'address',
                name: '_AAStaking',
                type: 'address'
            },
            {
                internalType: 'address',
                name: '_BBStaking',
                type: 'address'
            }
        ],
        name: 'setStakingRewards',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
        signature: '0x0986950b'
    },
    {
        inputs: [
            {
                internalType: 'address',
                name: '_strategy',
                type: 'address'
            },
            {
                internalType: 'address[]',
                name: '_incentiveTokens',
                type: 'address[]'
            }
        ],
        name: 'setStrategy',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
        signature: '0xf22ff9f4'
    },
    {
        inputs: [
            {
                internalType: 'uint256',
                name: '_unlentPerc',
                type: 'uint256'
            }
        ],
        name: 'setUnlentPerc',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
        signature: '0x1cf7a8ff'
    },
    {
        inputs: [],
        name: 'skipDefaultCheck',
        outputs: [
            {
                internalType: 'bool',
                name: '',
                type: 'bool'
            }
        ],
        stateMutability: 'view',
        type: 'function',
        constant: true,
        signature: '0x1ed4fd97'
    },
    {
        inputs: [],
        name: 'strategy',
        outputs: [
            {
                internalType: 'address',
                name: '',
                type: 'address'
            }
        ],
        stateMutability: 'view',
        type: 'function',
        constant: true,
        signature: '0xa8c62e76'
    },
    {
        inputs: [],
        name: 'strategyToken',
        outputs: [
            {
                internalType: 'address',
                name: '',
                type: 'address'
            }
        ],
        stateMutability: 'view',
        type: 'function',
        constant: true,
        signature: '0x747efea1'
    },
    {
        inputs: [],
        name: 'token',
        outputs: [
            {
                internalType: 'address',
                name: '',
                type: 'address'
            }
        ],
        stateMutability: 'view',
        type: 'function',
        constant: true,
        signature: '0xfc0c546a'
    },
    {
        inputs: [],
        name: 'trancheAPRSplitRatio',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function',
        constant: true,
        signature: '0x085a2b78'
    },
    {
        inputs: [],
        name: 'trancheIdealWeightRatio',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function',
        constant: true,
        signature: '0x25f66adf'
    },
    {
        inputs: [
            {
                internalType: 'address',
                name: '_tranche',
                type: 'address'
            }
        ],
        name: 'tranchePrice',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function',
        constant: true,
        signature: '0xa219d218'
    },
    {
        inputs: [
            {
                internalType: 'address',
                name: 'newOwner',
                type: 'address'
            }
        ],
        name: 'transferOwnership',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
        signature: '0xf2fde38b'
    },
    {
        inputs: [
            {
                internalType: 'address',
                name: '_token',
                type: 'address'
            },
            {
                internalType: 'uint256',
                name: '_value',
                type: 'uint256'
            }
        ],
        name: 'transferToken',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
        signature: '0x1072cbea'
    },
    {
        inputs: [],
        name: 'unclaimedFees',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function',
        constant: true,
        signature: '0x734d8287'
    },
    {
        inputs: [],
        name: 'unlentPerc',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function',
        constant: true,
        signature: '0x92b29be3'
    },
    {
        inputs: [],
        name: 'unpause',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
        signature: '0x3f4ba83a'
    },
    {
        inputs: [
            {
                internalType: 'address',
                name: '_tranche',
                type: 'address'
            }
        ],
        name: 'virtualPrice',
        outputs: [
            {
                internalType: 'uint256',
                name: '_virtualPrice',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function',
        constant: true,
        signature: '0x9290d427'
    },
    {
        inputs: [],
        name: 'weth',
        outputs: [
            {
                internalType: 'address',
                name: '',
                type: 'address'
            }
        ],
        stateMutability: 'view',
        type: 'function',
        constant: true,
        signature: '0x3fc8cef3'
    },
    {
        inputs: [
            {
                internalType: 'uint256',
                name: '_amount',
                type: 'uint256'
            }
        ],
        name: 'withdrawAA',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'nonpayable',
        type: 'function',
        signature: '0x9af64854'
    },
    {
        inputs: [
            {
                internalType: 'uint256',
                name: '_amount',
                type: 'uint256'
            }
        ],
        name: 'withdrawBB',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'nonpayable',
        type: 'function',
        signature: '0x99abe5e8'
    }
];
const CDO_MAIN_V4_ABI = [
    {
        inputs: [],
        stateMutability: 'nonpayable',
        type: 'constructor'
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: 'address',
                name: 'contractAddress',
                type: 'address'
            },
            {
                indexed: true,
                internalType: 'address',
                name: 'user',
                type: 'address'
            },
            {
                indexed: false,
                internalType: 'uint256',
                name: 'susdeAmount',
                type: 'uint256'
            }
        ],
        name: 'NewCooldownRequestContract',
        type: 'event'
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: 'address',
                name: 'previousOwner',
                type: 'address'
            },
            {
                indexed: true,
                internalType: 'address',
                name: 'newOwner',
                type: 'address'
            }
        ],
        name: 'OwnershipTransferred',
        type: 'event'
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: false,
                internalType: 'address',
                name: 'account',
                type: 'address'
            }
        ],
        name: 'Paused',
        type: 'event'
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: false,
                internalType: 'address',
                name: 'account',
                type: 'address'
            }
        ],
        name: 'Unpaused',
        type: 'event'
    },
    {
        inputs: [],
        name: 'AAStaking',
        outputs: [
            {
                internalType: 'address',
                name: '',
                type: 'address'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [],
        name: 'AATranche',
        outputs: [
            {
                internalType: 'address',
                name: '',
                type: 'address'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [],
        name: 'BBStaking',
        outputs: [
            {
                internalType: 'address',
                name: '',
                type: 'address'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [],
        name: 'BBTranche',
        outputs: [
            {
                internalType: 'address',
                name: '',
                type: 'address'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [],
        name: 'FULL_ALLOC',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [],
        name: 'AA_RATIO_LIM_UP',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [],
        name: 'AA_RATIO_LIM_DOWN',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [],
        name: 'MAX_FEE',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [],
        name: 'ONE_TRANCHE_TOKEN',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [
            {
                internalType: 'uint256',
                name: '_limit',
                type: 'uint256'
            }
        ],
        name: '_setLimit',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function'
    },
    {
        inputs: [],
        name: 'allowAAWithdraw',
        outputs: [
            {
                internalType: 'bool',
                name: '',
                type: 'bool'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [],
        name: 'allowBBWithdraw',
        outputs: [
            {
                internalType: 'bool',
                name: '',
                type: 'bool'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [
            {
                internalType: 'uint256',
                name: '_amount',
                type: 'uint256'
            }
        ],
        name: 'depositAA',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'nonpayable',
        type: 'function'
    },
    {
        inputs: [
            {
                internalType: 'uint256',
                name: '_amount',
                type: 'uint256'
            },
            {
                internalType: 'address',
                name: '_referral',
                type: 'address'
            }
        ],
        name: 'depositAARef',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'nonpayable',
        type: 'function'
    },
    {
        inputs: [
            {
                internalType: 'uint256',
                name: '_amount',
                type: 'uint256'
            }
        ],
        name: 'depositBB',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'nonpayable',
        type: 'function'
    },
    {
        inputs: [
            {
                internalType: 'uint256',
                name: '_amount',
                type: 'uint256'
            },
            {
                internalType: 'address',
                name: '_referral',
                type: 'address'
            }
        ],
        name: 'depositBBRef',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'nonpayable',
        type: 'function'
    },
    {
        inputs: [],
        name: 'emergencyShutdown',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function'
    },
    {
        inputs: [],
        name: 'fee',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [],
        name: 'feeReceiver',
        outputs: [
            {
                internalType: 'address',
                name: '',
                type: 'address'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [
            {
                internalType: 'address',
                name: '_tranche',
                type: 'address'
            }
        ],
        name: 'getApr',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [],
        name: 'getContractValue',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [],
        name: 'getCurrentAARatio',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [
            {
                internalType: 'address',
                name: '_tranche',
                type: 'address'
            }
        ],
        name: 'getIdealApr',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [],
        name: 'getIncentiveTokens',
        outputs: [
            {
                internalType: 'address[]',
                name: '',
                type: 'address[]'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [],
        name: 'governanceRecoveryFund',
        outputs: [
            {
                internalType: 'address',
                name: '',
                type: 'address'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [],
        name: 'guardian',
        outputs: [
            {
                internalType: 'address',
                name: '',
                type: 'address'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [
            {
                internalType: 'bool',
                name: '_skipRedeem',
                type: 'bool'
            },
            {
                internalType: 'bool',
                name: '_skipIncentivesUpdate',
                type: 'bool'
            },
            {
                internalType: 'bool',
                name: '_skipFeeDeposit',
                type: 'bool'
            },
            {
                internalType: 'bool[]',
                name: '_skipReward',
                type: 'bool[]'
            },
            {
                internalType: 'uint256[]',
                name: '_minAmount',
                type: 'uint256[]'
            },
            {
                internalType: 'uint256[]',
                name: '_sellAmounts',
                type: 'uint256[]'
            }
        ],
        name: 'harvest',
        outputs: [
            {
                internalType: 'uint256[]',
                name: '_soldAmounts',
                type: 'uint256[]'
            },
            {
                internalType: 'uint256[]',
                name: '_swappedAmounts',
                type: 'uint256[]'
            }
        ],
        stateMutability: 'nonpayable',
        type: 'function'
    },
    {
        inputs: [],
        name: 'idealRange',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [],
        name: 'latestHarvestBlock',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        name: 'incentiveTokens',
        outputs: [
            {
                internalType: 'address',
                name: '',
                type: 'address'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [
            {
                internalType: 'uint256',
                name: '_limit',
                type: 'uint256'
            },
            {
                internalType: 'address',
                name: '_guardedToken',
                type: 'address'
            },
            {
                internalType: 'address',
                name: '_governanceFund',
                type: 'address'
            },
            {
                internalType: 'address',
                name: '_owner',
                type: 'address'
            },
            {
                internalType: 'address',
                name: '_rebalancer',
                type: 'address'
            },
            {
                internalType: 'address',
                name: '_strategy',
                type: 'address'
            },
            {
                internalType: 'uint256',
                name: '_trancheAPRSplitRatio',
                type: 'uint256'
            },
            {
                internalType: 'uint256',
                name: '_trancheIdealWeightRatio',
                type: 'uint256'
            },
            {
                internalType: 'address[]',
                name: '_incentiveTokens',
                type: 'address[]'
            }
        ],
        name: 'initialize',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function'
    },
    {
        inputs: [],
        name: 'isAYSActive',
        outputs: [
            {
                internalType: 'bool',
                name: '',
                type: 'bool'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [],
        name: 'lastNAVAA',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [],
        name: 'lastNAVBB',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [],
        name: 'lastStrategyPrice',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [],
        name: 'limit',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [
            {
                internalType: 'uint256',
                name: '_amount',
                type: 'uint256'
            },
            {
                internalType: 'bool',
                name: '_revertIfNeeded',
                type: 'bool'
            }
        ],
        name: 'liquidate',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'nonpayable',
        type: 'function'
    },
    {
        inputs: [],
        name: 'oneToken',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [],
        name: 'owner',
        outputs: [
            {
                internalType: 'address',
                name: '',
                type: 'address'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [],
        name: 'pause',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function'
    },
    {
        inputs: [],
        name: 'paused',
        outputs: [
            {
                internalType: 'bool',
                name: '',
                type: 'bool'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [],
        name: 'priceAA',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [],
        name: 'priceBB',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [],
        name: 'rebalancer',
        outputs: [
            {
                internalType: 'address',
                name: '',
                type: 'address'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [],
        name: 'releaseBlocksPeriod',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [],
        name: 'renounceOwnership',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function'
    },
    {
        inputs: [],
        name: 'revertIfTooLow',
        outputs: [
            {
                internalType: 'bool',
                name: '',
                type: 'bool'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [
            {
                internalType: 'bool',
                name: '_allowed',
                type: 'bool'
            }
        ],
        name: 'setAllowAAWithdraw',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function'
    },
    {
        inputs: [
            {
                internalType: 'bool',
                name: '_allowed',
                type: 'bool'
            }
        ],
        name: 'setAllowBBWithdraw',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function'
    },
    {
        inputs: [
            {
                internalType: 'uint256',
                name: '_fee',
                type: 'uint256'
            }
        ],
        name: 'setFee',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function'
    },
    {
        inputs: [
            {
                internalType: 'address',
                name: '_feeReceiver',
                type: 'address'
            }
        ],
        name: 'setFeeReceiver',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function'
    },
    {
        inputs: [
            {
                internalType: 'address',
                name: '_guardian',
                type: 'address'
            }
        ],
        name: 'setGuardian',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function'
    },
    {
        inputs: [
            {
                internalType: 'uint256',
                name: '_idealRange',
                type: 'uint256'
            }
        ],
        name: 'setIdealRange',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function'
    },
    {
        inputs: [
            {
                internalType: 'address[]',
                name: '_incentiveTokens',
                type: 'address[]'
            }
        ],
        name: 'setIncentiveTokens',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function'
    },
    {
        inputs: [
            {
                internalType: 'bool',
                name: '_isStkAAVEActive',
                type: 'bool'
            }
        ],
        name: 'setIsStkAAVEActive',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function'
    },
    {
        inputs: [
            {
                internalType: 'address',
                name: '_rebalancer',
                type: 'address'
            }
        ],
        name: 'setRebalancer',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function'
    },
    {
        inputs: [
            {
                internalType: 'uint256',
                name: '_releaseBlocksPeriod',
                type: 'uint256'
            }
        ],
        name: 'setReleaseBlocksPeriod',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function'
    },
    {
        inputs: [
            {
                internalType: 'bool',
                name: '_allowed',
                type: 'bool'
            }
        ],
        name: 'setRevertIfTooLow',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function'
    },
    {
        inputs: [
            {
                internalType: 'bool',
                name: '_allowed',
                type: 'bool'
            }
        ],
        name: 'setSkipDefaultCheck',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function'
    },
    {
        inputs: [
            {
                internalType: 'address',
                name: '_AAStaking',
                type: 'address'
            },
            {
                internalType: 'address',
                name: '_BBStaking',
                type: 'address'
            }
        ],
        name: 'setStakingRewards',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function'
    },
    {
        inputs: [
            {
                internalType: 'address',
                name: '_strategy',
                type: 'address'
            },
            {
                internalType: 'address[]',
                name: '_incentiveTokens',
                type: 'address[]'
            }
        ],
        name: 'setStrategy',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function'
    },
    {
        inputs: [
            {
                internalType: 'uint256',
                name: '_unlentPerc',
                type: 'uint256'
            }
        ],
        name: 'setUnlentPerc',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function'
    },
    {
        inputs: [],
        name: 'skipDefaultCheck',
        outputs: [
            {
                internalType: 'bool',
                name: '',
                type: 'bool'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [],
        name: 'strategy',
        outputs: [
            {
                internalType: 'address',
                name: '',
                type: 'address'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [],
        name: 'strategyToken',
        outputs: [
            {
                internalType: 'address',
                name: '',
                type: 'address'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [],
        name: 'token',
        outputs: [
            {
                internalType: 'address',
                name: '',
                type: 'address'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [],
        name: 'trancheAPRSplitRatio',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [],
        name: 'trancheIdealWeightRatio',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [
            {
                internalType: 'address',
                name: '_tranche',
                type: 'address'
            }
        ],
        name: 'tranchePrice',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [
            {
                internalType: 'address',
                name: 'newOwner',
                type: 'address'
            }
        ],
        name: 'transferOwnership',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function'
    },
    {
        inputs: [
            {
                internalType: 'address',
                name: '_token',
                type: 'address'
            },
            {
                internalType: 'uint256',
                name: '_value',
                type: 'uint256'
            }
        ],
        name: 'transferToken',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function'
    },
    {
        inputs: [],
        name: 'unclaimedFees',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [],
        name: 'unlentPerc',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [],
        name: 'unpause',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function'
    },
    {
        inputs: [
            {
                internalType: 'address',
                name: '_tranche',
                type: 'address'
            }
        ],
        name: 'virtualPrice',
        outputs: [
            {
                internalType: 'uint256',
                name: '_virtualPrice',
                type: 'uint256'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [],
        name: 'weth',
        outputs: [
            {
                internalType: 'address',
                name: '',
                type: 'address'
            }
        ],
        stateMutability: 'view',
        type: 'function'
    },
    {
        inputs: [
            {
                internalType: 'uint256',
                name: '_amount',
                type: 'uint256'
            }
        ],
        name: 'withdrawAA',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'nonpayable',
        type: 'function'
    },
    {
        inputs: [
            {
                internalType: 'uint256',
                name: '_amount',
                type: 'uint256'
            }
        ],
        name: 'withdrawBB',
        outputs: [
            {
                internalType: 'uint256',
                name: '',
                type: 'uint256'
            }
        ],
        stateMutability: 'nonpayable',
        type: 'function'
    }
];

//# sourceMappingURL=cdo-abis.js.map