/**
 * GAUNTLET ABIs
 * Auto-generated by abi-migration script
 */ "use strict";
Object.defineProperty(exports, "__esModule", {
    value: true
});
Object.defineProperty(exports, "GAUNTLET_MAIN_V1_ABI", {
    enumerable: true,
    get: function() {
        return GAUNTLET_MAIN_V1_ABI;
    }
});
const GAUNTLET_MAIN_V1_ABI = [];

//# sourceMappingURL=gauntlet-abis.js.map