/**
 * ORACLE ABIs
 * Auto-generated by abi-migration script
 */
import { AbiContract } from '../../core';
export declare const ORACLE_AaveV2_V1_ABI: AbiContract;
export declare const ORACLE_Clearpool_V1_ABI: AbiContract;
export declare const ORACLE_PendleSY_V1_ABI: AbiContract;
export declare const ORACLE_PendlePT_V1_ABI: AbiContract;
export declare const ORACLE_Balancer_V1_ABI: AbiContract;
export declare const ORACLE_Euler_V1_ABI: AbiContract;
