/**
 * PARETO_DOLLAR ABIs
 * Auto-generated by abi-migration script
 */
import { AbiContract } from '../../core';
export declare const PARETO_DOLLAR_MAIN_V1_ABI: AbiContract;
export declare const PARETO_DOLLAR_QUEUE_V1_ABI: AbiContract;
export declare const PARETO_DOLLAR_STAKING_V1_ABI: AbiContract;
