/**
 * POOL ABIs
 * Auto-generated by abi-migration script
 */
import { AbiContract } from '../../core';
export declare const POOL_Compound_V1_ABI: AbiContract;
export declare const POOL_AaveV2_V1_ABI: AbiContract;
export declare const POOL_Idle_V1_ABI: AbiContract;
export declare const POOL_Gearbox_V1_ABI: AbiContract;
export declare const POOL_InstadApp_V1_ABI: AbiContract;
export declare const POOL_Compound_V2_ABI: AbiContract;
export declare const POOL_Morpho_V1_ABI: AbiContract;
export declare const POOL_Ethena_V1_ABI: AbiContract;
export declare const POOL_PendleLP_V1_ABI: AbiContract;
export declare const POOL_PendlePT_V1_ABI: AbiContract;
export declare const POOL_PendleYT_V1_ABI: AbiContract;
export declare const POOL_Sky_V1_ABI: AbiContract;
export declare const POOL_Balancer_V1_ABI: AbiContract;
export declare const POOL_BalancerGauge_V1_ABI: AbiContract;
export declare const POOL_NapierLP_V1_ABI: AbiContract;
export declare const POOL_NapierYT_V1_ABI: AbiContract;
export declare const POOL_NapierPT_V1_ABI: AbiContract;
export declare const POOL_Euler_V1_ABI: AbiContract;
export declare const POOL_TermFinance_V1_ABI: AbiContract;
